workflows:
  ios-appstore:
    name: iOS App Store
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Build iOS
        script: |
          flutter build ipa --release \
            --export-options-plist=ios/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        key_id: P3D22DWV9P
        issuer_id: 7f99861d-5fdd-4a80-a22c-652f43960eae
