// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// ⚠️ GÜVENLİK UYARISI: Aşağıdaki API Key Firebase Console'dan restrict edilmelidir!
// Git: Firebase Console → Project Settings → General → API Key → Key restrictions
// - Android: Sadece uygulamanın package name'ini (com.cizreapp.app)
// - iOS: Sadece uygulamanın bundle ID'sini kısıtlayın

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjHPmfsQrpXAgikxcP8fjWvHhP6q5Ynm0',
    appId: '1:224517445508:android:64a88239bfdc5591cbafd1',
    messagingSenderId: '224517445508',
    projectId: 'cizreapp-3b9a4',
    storageBucket: 'cizreapp-3b9a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjHPmfsQrpXAgikxcP8fjWvHhP6q5Ynm0',
    appId: '1:224517445508:ios:64a88239bfdc5591cbafd1',
    messagingSenderId: '224517445508',
    projectId: 'cizreapp-3b9a4',
    storageBucket: 'cizreapp-3b9a4.firebasestorage.app',
    iosBundleId: 'com.cizreapp.app',
  );

  // Firebase Web Configuration
  // Firebase Console → Project Settings → General → Your apps → Web app kısmından alınmıştır
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjHPmfsQrpXAgikxcP8fjWvHhP6q5Ynm0',
    appId: '1:224517445508:web:abc123def456',
    messagingSenderId: '224517445508',
    projectId: 'cizreapp-3b9a4',
    storageBucket: 'cizreapp-3b9a4.firebasestorage.app',
    authDomain: 'cizreapp-3b9a4.firebaseapp.com',
    measurementId: 'G-XXXXXXXXXX',
    databaseURL: 'https://cizreapp-3b9a4-default-rtdb.firebaseio.com',
  );
}
