# Uncomment this line to define a global platform for this project
platform :ios, '15.0'

# CocoaPods plugins for Flutter
flutter_application_path = File.join(File.dirname(__FILE__), '.symlinks', '..')
load File.join(flutter_application_path, 'ios', 'Flutter', 'Podfile')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Flutter dependencies
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
