-- Admin > Loglar ekranını cihazdaki yerel Hive kayıtları yerine merkezi,
-- kalıcı Supabase verileriyle besler.

CREATE TABLE IF NOT EXISTS public.app_analytics_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  event_type text NOT NULL CHECK (length(btrim(event_type)) BETWEEN 1 AND 100),
  entity_id text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  duration_ms integer CHECK (duration_ms IS NULL OR duration_ms >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.app_analytics_events ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_app_analytics_events_created_at
  ON public.app_analytics_events (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_app_analytics_events_type_created
  ON public.app_analytics_events (event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_app_analytics_events_entity_created
  ON public.app_analytics_events (entity_id, created_at DESC)
  WHERE entity_id IS NOT NULL;

DROP POLICY IF EXISTS "Users can insert own analytics events"
  ON public.app_analytics_events;
CREATE POLICY "Users can insert own analytics events"
  ON public.app_analytics_events
  FOR INSERT
  TO authenticated
  WITH CHECK (user_id = (SELECT auth.uid()));

REVOKE ALL ON TABLE public.app_analytics_events FROM PUBLIC, anon;
GRANT INSERT ON TABLE public.app_analytics_events TO authenticated;
GRANT ALL ON TABLE public.app_analytics_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.app_analytics_events_id_seq
  TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.admin_logs_data(
  p_recent_user_limit integer DEFAULT 20,
  p_error_limit integer DEFAULT 20,
  p_most_viewed_limit integer DEFAULT 5
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_now timestamptz := now();
  v_today_start timestamptz := date_trunc('day', v_now AT TIME ZONE 'UTC') AT TIME ZONE 'UTC';
  v_recent_user_limit integer := LEAST(GREATEST(COALESCE(p_recent_user_limit, 20), 1), 200);
  v_error_limit integer := LEAST(GREATEST(COALESCE(p_error_limit, 20), 1), 200);
  v_most_viewed_limit integer := LEAST(GREATEST(COALESCE(p_most_viewed_limit, 5), 1), 50);
BEGIN
  IF NOT private.current_user_is_admin() THEN
    RAISE EXCEPTION 'admin_logs_data: not admin' USING ERRCODE = '42501';
  END IF;

  RETURN jsonb_build_object(
    'online', (SELECT count(*) FROM public.profiles WHERE last_seen >= v_now - interval '5 minutes'),
    'dau', (SELECT count(*) FROM public.profiles WHERE last_seen >= v_today_start),
    'wau', (SELECT count(*) FROM public.profiles WHERE last_seen >= v_now - interval '7 days'),
    'mau', (SELECT count(*) FROM public.profiles WHERE last_seen >= v_now - interval '30 days'),
    'totalUsers', (SELECT count(*) FROM public.profiles),
    'newToday', (SELECT count(*) FROM public.profiles WHERE created_at >= v_today_start),
    'inactive', (SELECT count(*) FROM public.profiles WHERE last_seen IS NULL OR last_seen < v_now - interval '30 days'),
    'totalEvents', (SELECT count(*) FROM public.app_analytics_events),
    'avgViewDuration', COALESCE((
      SELECT round(avg(duration_ms))::bigint
      FROM public.app_analytics_events
      WHERE event_type = 'post_view' AND duration_ms IS NOT NULL
    ), 0),
    'errorCount', (SELECT count(*) FROM public.app_analytics_events WHERE event_type = 'error'),
    'recentUsers', COALESCE((
      SELECT jsonb_agg(to_jsonb(u) ORDER BY u.last_seen DESC NULLS LAST)
      FROM (
        SELECT id, username, full_name, avatar_url,
               (last_seen >= v_now - interval '5 minutes') AS is_online,
               last_seen
        FROM public.profiles
        ORDER BY last_seen DESC NULLS LAST
        LIMIT v_recent_user_limit
      ) AS u
    ), '[]'::jsonb),
    'errors', COALESCE((
      SELECT jsonb_agg(to_jsonb(e) ORDER BY e.created_at DESC)
      FROM (
        SELECT id, event_type, entity_id, metadata, duration_ms, created_at
        FROM public.app_analytics_events
        WHERE event_type = 'error'
        ORDER BY created_at DESC
        LIMIT v_error_limit
      ) AS e
    ), '[]'::jsonb),
    'errorTypeCounts', COALESCE((
      SELECT jsonb_object_agg(error_type, event_count)
      FROM (
        SELECT COALESCE(NULLIF(metadata ->> 'type', ''), 'Bilinmeyen') AS error_type,
               count(*) AS event_count
        FROM public.app_analytics_events
        WHERE event_type = 'error'
        GROUP BY 1
      ) AS error_counts
    ), '{}'::jsonb),
    'hourlyDistribution', COALESCE((
      SELECT jsonb_object_agg(event_hour::text, event_count)
      FROM (
        SELECT extract(hour FROM created_at AT TIME ZONE 'Europe/Istanbul')::integer AS event_hour,
               count(*) AS event_count
        FROM public.app_analytics_events
        GROUP BY 1
      ) AS hourly
    ), '{}'::jsonb),
    'mostViewedPosts', COALESCE((
      SELECT jsonb_object_agg(entity_id, view_count)
      FROM (
        SELECT entity_id, count(*) AS view_count
        FROM public.app_analytics_events
        WHERE event_type = 'post_view' AND entity_id IS NOT NULL
        GROUP BY entity_id
        ORDER BY view_count DESC, entity_id
        LIMIT v_most_viewed_limit
      ) AS viewed
    ), '{}'::jsonb)
  );
END;
$$;

REVOKE ALL ON FUNCTION public.admin_logs_data(integer, integer, integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_logs_data(integer, integer, integer)
  TO authenticated, service_role;

NOTIFY pgrst, 'reload schema';
