-- App About Settings Table
-- Bu tablo "Hakkında" ekranındaki bilgileri tutar ve admin tarafından düzenlenebilir

-- Tablo oluştur
CREATE TABLE IF NOT EXISTS public.app_about_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app_name TEXT NOT NULL DEFAULT 'Cizre App',
  app_slogan TEXT NOT NULL DEFAULT 'Cizre''nin En Büyük Alışveriş Platformu',
  app_description TEXT NOT NULL,
  app_features TEXT[] NOT NULL DEFAULT ARRAY[
    'Mağaza ve ürün yönetimi',
    'Sipariş takibi',
    'Sosyal paylaşım ve etkileşim',
    'Anlık mesajlaşma',
    'Favori ürünler ve mağazalar',
    'Ürün değerlendirme sistemi'
  ],
  contact_email TEXT NOT NULL DEFAULT 'destek@cizreapp.com',
  website_url TEXT NOT NULL DEFAULT 'https://cizreapp.com',
  support_phone TEXT,
  terms_of_service TEXT NOT NULL,
  privacy_policy TEXT NOT NULL,
  version_number TEXT NOT NULL DEFAULT '1.0.0',
  build_number TEXT NOT NULL DEFAULT '1',
  social_media_links JSONB DEFAULT '{
    "instagram": "",
    "twitter": "",
    "facebook": "",
    "youtube": ""
  }'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- İlk kaydı oluştur
INSERT INTO public.app_about_settings (
  app_name,
  app_slogan,
  app_description,
  terms_of_service,
  privacy_policy
) VALUES (
  'Cizre App',
  'Cizre''nin En Büyük Alışveriş Platformu',
  'Cizre App, Cizre ve çevresindeki kullanıcıların güvenli bir şekilde alışveriş yapabileceği, ürün satışı gerçekleştirebileceği ve sosyal etkileşimde bulunabileceği kapsamlı bir platformdur.',
  '1. KABUL EDİLEN KOŞULLAR

Cizre App''i kullanarak aşağıdaki koşulları kabul etmiş sayılırsınız.

2. KULLANICI SORUMLULUKLARI

• Gerçek ve doğru bilgiler sağlamak
• Başka kullanıcıların haklarına saygı göstermek
• Uygulamayı yasa dışı amaçlarla kullanmamak
• Başka kullanıcıların hesaplarına izinsiz erişmemek

3. MAĞAZA VE ÜRÜN SATIŞI

• Satıcılar, sattıkları ürünlerden sorumludur
• Ürün açıklamaları doğru olmalıdır
• Teslimat sürelerine uyulmalıdır
• Haksız rekabete girilemez

4. YASAKLI İÇERİKLER

Aşağıdaki içerikler yasaktır:
• Yasa dışı ürünler
• Uyuşturucu ve silahlar
• Sahte ürünler
• Telif hakkı ihlal eden içerikler
• Müstehcen içerikler

5. SİPARİŞLER VE ÖDEMELER

• Siparişler ödeme alındıktan sonra işleme alınır
• İade koşulları ürün tipine göre değişir
• Ödeme bilgileri güvendedir

6. SORUMLULUK REDDI

Cizre App, kullanıcıların eylemlerinden sorumlu değildir.

7. HAKLARIMIZ

Bu koşulları her zaman değiştirme hakkımız saklıdır.',
  'GİZLİLİK POLİTİKASI

1. VERİ TOPLAMA

Aşağıdaki verileri toplayabiliriz:
• Hesap bilgileri (ad, e-posta, telefon)
• Profil bilgileri (fotoğraf, bio)
• Konum bilgileri (teslimat için)
• Kullanım verileri
• Cihaz bilgileri

2. VERİ KULLANIMI

Verilerinizi şunlar için kullanırız:
• Hizmetleri sunmak
• Siparişleri işlemek
• İletişim sağlamak
• Güvenliği sağlamak
• Hizmetleri iyileştirmek

3. VERİ PAYLAŞIMI

Verileriniz:
• Asla üçüncü taraflarla satılmaz
• Sadece yasal gerekliliklerde paylaşılır
• Hizmet sağlayıcılarla güvenli şekilde paylaşılır

4. VERİ GÜVENLİĞİ

• SSL şifreleme kullanıyoruz
• Verileriniz güvenli sunucularda saklanır
• Düzenli güvenlik denetimleri yapılır

5. KULLANICI HAKLARI

• Verilerinizi görme
• Verilerinizi düzeltme
• Verilerinizi silme
• Hesabınızı silme

6. ÇEREZLER

Çerezleri kullanım deneyimini iyileştirmek için kullanırız.

7. İLETİŞİM

Gizlilik ile ilgili sorularınız için:
destek@cizreapp.com

Bu politika 01.01.2024 tarihinde yürürlüğe girmiştir.'
)
ON CONFLICT DO NOTHING;

-- updated_at trigger
CREATE OR REPLACE FUNCTION update_app_about_settings_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER app_about_settings_updated_at
  BEFORE UPDATE ON public.app_about_settings
  FOR EACH ROW
  EXECUTE FUNCTION update_app_about_settings_updated_at();

-- RLS Politikaları
ALTER TABLE public.app_about_settings ENABLE ROW LEVEL SECURITY;

-- Herkes okuyabilir
CREATE POLICY "app_about_settings_select_policy"
ON public.app_about_settings
FOR SELECT
TO authenticated
USING (true);

-- Sadece admin güncelleyebilir
CREATE POLICY "app_about_settings_update_policy"
ON public.app_about_settings
FOR UPDATE
TO authenticated
USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'))
WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
