-- Bot içerik kitaplığı tohumu (üretildi: scripts/gen_texts.py mantığı).
-- Tekrar çalıştırmak güvenlidir: md5(body) üzerindeki tekil indeks
-- yinelenen metni sessizce atlar.
INSERT INTO public.bot_content_library (body, tone) VALUES
  ('Termometre 47 gösteriyor. Dışarı çıkacaksanız akşamüstünü bekleyin derim, bu saatte gölge bile serinletmiyor.', 'hava'),
  ('Sabah altıda bile hava ılık. Cizre''de yaz erken uyanıyor.', 'hava'),
  ('Akşam bir rüzgâr çıktı, bütün günün yorgunluğunu alıp götürdü.', 'hava'),
  ('Klima sabahtan beri çalışıyor ama içerisi bir türlü serinlemedi. Böylesini az hatırlıyorum.', 'hava'),
  ('Yağmur yağdı! Toprağın kokusunu içime çektim. Burada yağmur bayram gibi bir şey.', 'hava'),
  ('Kışın havası bambaşka oluyor burada. Ceketsiz yürüdüm, tadına doyulmuyor.', 'hava'),
  ('Bugün toz var, göz gözü görmüyor. Astımı olan arkadaşlar dikkat etsin.', 'hava'),
  ('Gece serinliği çöktü, balkonda oturmanın tam zamanı.', 'hava'),
  ('Sıcaktan asfalt eriyor sanki. Ayakkabınızın tabanına dikkat 😅', 'hava'),
  ('İlk sonbahar rüzgârı esti bugün. İnsanın içi açılıyor.', 'hava'),
  ('Dicle kıyısında yürüyüş yaptım. Suyun sesi insanı bambaşka yapıyor.', 'doga'),
  ('Sabah sisi nehrin üstünde asılı kalmış. On dakika durup baktım, gitmek istemedim.', 'doga'),
  ('Cudi''nin eteklerinde gün batımı... Anlatmakla olmuyor, görmek lazım.', 'doga'),
  ('Nehir kenarındaki söğütler yeşerdi. Bahar geldi demektir.', 'doga'),
  ('Akşam serinliğinde köprüden geçerken durup suya baktım. Bu manzaraya alışamıyorum.', 'doga'),
  ('Bu şehrin en güzel saati, güneşin nehre değdiği o on dakika.', 'doga'),
  ('Yürüyüş yolunda bugün leylek gördüm. Mevsim döndü demek.', 'doga'),
  ('Sabahın ilk ışığında nehir bakır rengine dönüyor. Erken kalkanın kârı.', 'doga'),
  ('Bugün çok güzel bir haber aldım, içim içime sığmıyor. Hayırlısı olsun 🙏', 'mutlu'),
  ('Komşunun çocuğu üniversiteyi kazandı, bütün sokak sevindi. Helal olsun ona.', 'mutlu'),
  ('Yıllardır görüşmediğim bir arkadaşımla çarşıda karşılaştım. Gün güzel başladı.', 'mutlu'),
  ('Küçük şeylerden mutlu olmayı öğrendim: sıcak çay, serin gölge, iyi bir sohbet.', 'mutlu'),
  ('Bugün hiçbir şey ters gitmedi. Böyle günler de varmış demek 😊', 'mutlu'),
  ('Düğün vardı akşam, sabaha kadar halay çektik. Ayaklarım ağrıyor ama değdi.', 'mutlu'),
  ('Bayram sabahı sokakların o hali... Yılın en güzel sabahı bence.', 'mutlu'),
  ('Uzun zamandır beklediğim iş oldu. Emeği geçen herkese teşekkür ederim.', 'mutlu'),
  ('Torunum ilk adımını attı bugün. Video çekmeye elim titredi.', 'mutlu'),
  ('Bir selam bu kadar zor mu geldi? Aynı sokakta oturuyoruz, geçip gidiyorsun.', 'sitem'),
  ('Arayan soran yok. İnsan bir ''nasılsın'' der, o kadar.', 'sitem'),
  ('Herkes kendi telaşında. Eskiden kapı komşusu hasta olsa haberimiz olurdu.', 'sitem'),
  ('Yardım isteyince herkes meşgul, iş bitince herkes yanında. Not aldım.', 'sitem'),
  ('Sözünde durmayan insanla bir daha iş yapılmaz, öğrendim artık.', 'sitem'),
  ('Kırk yıllık dostluk bir mesajla bitmez sanıyordum. Yanılmışım.', 'sitem'),
  ('Bize gelmeyi unuttunuz. Kapımız hâlâ açık, haberiniz olsun.', 'sitem'),
  ('Kimseden bir şey beklemeyince insan daha rahat oluyormuş.', 'sitem'),
  ('Verdiğin sözü tutmadın diye değil, hiç açıklama yapmadığın için kırgınım.', 'sitem'),
  ('Bu ay masraflar yine beklediğimden fazla çıktı. Nasıl denkleştireceğim bilmiyorum.', 'kaygi'),
  ('Çocukların okul masrafını düşününce uykum kaçıyor açıkçası.', 'kaygi'),
  ('Sağlık kontrolüne gideceğim, sonucu bekliyorum. İçim rahat değil.', 'kaygi'),
  ('İşler durgun. Umarım önümüzdeki ay açılır.', 'kaygi'),
  ('Kira zammını duyunca ne diyeceğimi bilemedim. Herkese kolay gelsin.', 'kaygi'),
  ('Gençler iş bulamıyor, en çok buna üzülüyorum.', 'kaygi'),
  ('Yaşlı komşumuz tek başına kalıyor. Bir ara uğrayayım diyorum, aklımda hep o.', 'kaygi'),
  ('Sınav yaklaştı, çocuktan çok ben stres yapıyorum galiba.', 'kaygi'),
  ('Sokağın başındaki çukur büyüyor. Biri düşmeden çözülse iyi olur.', 'sikayet'),
  ('Su yine kesildi, haber de verilmedi. Bir bilgilendirme çok mu zor?', 'sikayet'),
  ('Elektrik gitti geldi, gitti geldi... Buzdolabına yazık oluyor.', 'sikayet'),
  ('Çöp konteynerleri günlerdir boşaltılmamış, sıcakta kokuyor.', 'sikayet'),
  ('Kaldırıma park edenler yüzünden bebek arabasıyla yürünmüyor.', 'sikayet'),
  ('Gece yarısı korna çalmanın anlamı ne, biri açıklasın.', 'sikayet'),
  ('İnternet iki gündür sürünüyor. Evden çalışan var, dikkate alınsa keşke.', 'sikayet'),
  ('Fiyatlar her hafta değişiyor, esnaf da şaşırmış durumda.', 'sikayet'),
  ('Otobüs saatleri bir türlü tutmuyor. Yarım saat bekledim yine.', 'sikayet'),
  ('Parktaki bankların yarısı kırık. Küçük bir bakım yeter aslında.', 'sikayet'),
  ('Kapının önünde bir kedi yatıyor, kalkmaya da niyeti yok. Ev sahibi o artık 🐈', 'sevimli'),
  ('Mahallenin çocukları bugün bana ''abla'' dedi, üç yaş gençleştim 😄', 'sevimli'),
  ('Kuşlar balkondaki saksıya yuva yapmış. Şimdi çiçeği sulamaya korkuyorum.', 'sevimli'),
  ('Bakkalın köpeği her sabah beni kapıda karşılıyor. Günün en iyi kısmı.', 'sevimli'),
  ('Yeğenim telefonu eline aldı, 500 fotoğraf çekmiş. Hepsi tavan fotoğrafı 😅', 'sevimli'),
  ('Komşunun kızı kapıya kurabiye bırakmış. Böyle şeyler insanı iyi ediyor.', 'sevimli'),
  ('Sokak kedisine mama aldım, gelip elimi kokladı sonra kaçtı. Yavaş yavaş dost oluyoruz.', 'sevimli'),
  ('Çocuk ''niye çalışıyorsun'' diye sordu. Cevap veremedim, haklı çünkü.', 'sevimli'),
  ('Eskiden akşamları sokakta oynardık, anneler pencereden seslenirdi. O ses hâlâ kulağımda.', 'nostalji'),
  ('Kışın soba başında toplanırdık. Şimdi herkes odasında, telefonunda.', 'nostalji'),
  ('Bu çarşıyı dedemle gezerdim. Dükkânların yarısı değişti, kokusu aynı kaldı.', 'nostalji'),
  ('İlkokul sıramın üstüne isim kazımıştım. Acaba duruyor mu hâlâ?', 'nostalji'),
  ('Eski düğünler başkaydı. Üç gün üç gece sürerdi, kimse acele etmezdi.', 'nostalji'),
  ('Nehre taş atıp seken sayısını sayardık. Rekorum yediydi 😄', 'nostalji'),
  ('Bir zamanlar mektup yazardık. Cevap gelene kadar geçen o bekleyiş bile güzeldi.', 'nostalji'),
  ('Yaz akşamları damda yatardık. Yıldızlar daha çoktu sanki.', 'nostalji'),
  ('Sabah altıda dükkânı açtım, ilk müşteri yedide geldi. Emeksiz kazanç yok.', 'esnaf'),
  ('Vadeli sattığım malın parasını hâlâ alamadım. Esnaflık zor iş.', 'esnaf'),
  ('Bugün siftahı geç yaptım ama bereketli oldu, şükür.', 'esnaf'),
  ('Müşteri ''düşünüp geleyim'' dedi, üç yıl oldu hâlâ düşünüyor 😄', 'esnaf'),
  ('Dükkânı yeniledim, gelip görün. Çay bizden.', 'esnaf'),
  ('Sanayide iş yoğun, akşama kadar başımı kaldıramadım.', 'esnaf'),
  ('Kaliteli mal pahalı gelir ama ucuzu iki kez aldırır. Hep söylerim.', 'esnaf'),
  ('Çırağım bugün ilk işini tek başına bitirdi. Gurur duydum.', 'esnaf'),
  ('Akşama içli köfte yaptım, tepsi boşaldı. Tarif isteyen olursa yazarım.', 'yemek'),
  ('Kahvaltıda taze ekmek, tereyağı, bal. Başka bir şey istemem.', 'yemek'),
  ('Kışlık salçayı kurdum, damda kuruyor. Bu iş sabır işi.', 'yemek'),
  ('Bugün mercimek çorbası içtim, annemin elinin tadı yok ama olsun.', 'yemek'),
  ('Fırından çıkan tepsinin kokusu bütün sokağa yayıldı 🍰', 'yemek'),
  ('Tandır ekmeği sıcakken yenir, soğuyunca aynı olmuyor.', 'yemek'),
  ('Nar ekşisi olmadan salata olmuyor, tartışmaya kapalı.', 'yemek'),
  ('Akşam yemeğine kalabalık geldik, sofra bereketliydi. Şükür.', 'yemek'),
  ('Komşumuzun kombisi bozulmuş, ustaya haber verdik. Böyle şeyler için varız.', 'dayanisma'),
  ('Mahallede ihtiyaç sahibi bir aile var. Elinden geleni yapan yazsın, koordine edelim.', 'dayanisma'),
  ('Kan bağışına gittim bugün. On beş dakika sürüyor, hepsi bu.', 'dayanisma'),
  ('Taşınan komşuya yardım ettik, yarım saatte bitti. Kalabalık güzel şey.', 'dayanisma'),
  ('Kitap topluyoruz, okula bağışlayacağız. Evinizde duran varsa haber verin.', 'dayanisma'),
  ('Yaşlı komşunun alışverişini beraber yapıyoruz artık. Zor değil, sadece akla gelmesi lazım.', 'dayanisma'),
  ('Sokağı beraber temizledik bugün. Bir saatte bambaşka oldu.', 'dayanisma'),
  ('Akşam maçı vardı, kaybettik ama keyifliydi. Haftaya rövanş ⚽', 'spor'),
  ('Sabah koşusuna başladım. İlk gün 2 kilometre, idare eder.', 'spor'),
  ('Halı sahada bu hafta yer kalmamış. Herkes formda galiba 😄', 'spor'),
  ('Çocukları spora yazdırın, ekrandan iyidir.', 'spor'),
  ('Dizim ağrıyor ama antrenmanı kaçırmadım. Disiplin bu olsa gerek.', 'spor'),
  ('Turnuvanın finali cumartesi. Gelin, kalabalık olsun.', 'spor'),
  ('Dün yardım eden isimsiz kardeşime teşekkür ederim. Allah razı olsun.', 'tesekkur'),
  ('Arabam yolda kaldı, iki kişi durup itti. İyi insanlar var hâlâ.', 'tesekkur'),
  ('Cüzdanımı bulup getiren gence çok teşekkür ederim. İçinde her şey duruyordu.', 'tesekkur'),
  ('Hastanedeki hemşire hanıma teşekkürler, çok ilgiliydi.', 'tesekkur'),
  ('Sabaha kadar çalışan temizlik görevlilerine selam olsun.', 'tesekkur'),
  ('İyi bir oto elektrikçisi arıyorum, önerisi olan var mı?', 'soru'),
  ('Çocuk için kurs arıyorum. Tavsiye edeceğiniz yer var mı?', 'soru'),
  ('Hafta sonu piknik için sakin bir yer önerir misiniz?', 'soru'),
  ('Buralarda ikinci el kitap satan bir yer var mı acaba?', 'soru'),
  ('Klima bakımını kime yaptırıyorsunuz? Fiyatlar çok değişken.', 'soru'),
  ('Akşam yemeği için nereyi önerirsiniz, misafirim var.', 'soru'),
  ('Kışlık odun/pelet için güvendiğiniz bir yer var mı?', 'soru'),
  ('Bugün erken kalktım, günün uzunluğuna şaşırdım.', 'gunluk'),
  ('Çay ocağında yarım saat oturdum, iyi geldi.', 'gunluk'),
  ('Listemde on madde vardı, üçünü yapabildim. Yarın devam.', 'gunluk'),
  ('Telefonu bir gün kapatsam ne olur diye düşünüyorum.', 'gunluk'),
  ('Yürüyerek gitmek arabayla gitmekten kısa sürdü. Trafik böyle bir şey.', 'gunluk'),
  ('Bugün hiçbir yere yetişemedim ama kimse de kızmadı, iyi ki.', 'gunluk'),
  ('Akşam kitap açtım, iki sayfada uyumuşum.', 'gunluk'),
  ('Kahve içmeyi bıraktım diyorum, üçüncüyü içiyorum ☕', 'gunluk'),
  ('Bugün çarşı çok kalabalıktı. Herkes bir telaşta.', 'gunluk'),
  ('Saç kestirdim, kimse fark etmedi. Klasik.', 'gunluk'),
  ('Sabah alarmı çalmadan uyandım. Bugün iyi geçecek galiba.', 'gunluk'),
  ('Bir işi ertelemek, o işi iki katına çıkarıyormuş. Test ettim, doğru.', 'gunluk'),
  ('Yeni açılan yerleri gezdim, şehir yavaş yavaş değişiyor.', 'sehir'),
  ('Tarihi köprüden geçerken hep aynı şeyi düşünüyorum: kaç kişi geçti buradan?', 'sehir'),
  ('Ulu Cami''nin avlusunda oturdum biraz. Sessizlik iyi geldi.', 'sehir'),
  ('Şehirde bisiklet yolu olsa, yazın bile kullanırdım.', 'sehir'),
  ('Akşamları sahil kenarı kalabalıklaşıyor, güzel oluyor.', 'sehir'),
  ('Kırmızı Medrese''ye uzun zamandır uğramamıştım. Yine etkilendim.', 'sehir'),
  ('Bu şehrin en büyük zenginliği insanı. Nereye gitsem söylüyorum.', 'sehir'),
  ('Sokak isimlerini yenilemişler, adres tarif etmek kolaylaştı.', 'sehir'),
  ('Silopi yolunda trafik akıcıydı bugün, şaşırdım.', 'sehir'),
  ('Bugün olmadıysa yarın olur. Acele etmeye gerek yok.', 'motivasyon'),
  ('Küçük adım da adımdır. Durmamak yeter.', 'motivasyon'),
  ('Kimse ilk günden ustalaşmadı. Sabır lazım, o kadar.', 'motivasyon'),
  ('İyilik yapmanın maliyeti yok, etkisi büyük.', 'motivasyon'),
  ('Şikâyet etmek kolay, bir şey yapmak zor. Zor olanı seçelim.', 'motivasyon'),
  ('Dün yapamadığın şeyi bugün deneyebilirsin. Sadece bu.', 'motivasyon')
ON CONFLICT DO NOTHING;

SELECT tone, count(*) AS adet FROM public.bot_content_library GROUP BY tone ORDER BY tone;
SELECT count(*) AS toplam_metin FROM public.bot_content_library;
