-- ai_settings tablosuna varsayılan satır ekle (yoksa)
INSERT INTO public.ai_settings (
  id,
  enabled,
  provider,
  text_model,
  vision_model,
  image_model,
  groq_text_model,
  groq_vision_model,
  openrouter_text_model,
  openrouter_vision_model,
  openrouter_image_model,
  openai_text_model,
  openai_vision_model,
  openai_image_model,
  daily_request_limit_per_user,
  daily_token_limit_per_user,
  max_messages_per_conversation,
  allow_image_upload,
  allow_image_generation,
  allow_camera_capture,
  system_prompt,
  temperature,
  max_output_tokens
) VALUES (
  1,
  true,
  'gemini',
  'gemini-2.0-flash',
  'gemini-2.0-flash',
  'imagen-3.0-generate-002',
  'llama-3.3-70b-versatile',
  'llama-3.2-90b-vision-preview',
  'google/gemini-2.0-flash-exp:free',
  'google/gemini-2.0-flash-exp:free',
  'stable-diffusion-xl',
  'gpt-4o-mini',
  'gpt-4o-mini',
  'dall-e-3',
  50,
  100000,
  100,
  true,
  true,
  true,
  'Sen CizreApp kullanıcılarına yardımcı olan bir Türkçe yapay zeka asistanısın.',
  0.7,
  2048
) ON CONFLICT (id) DO NOTHING;
